/*******************************************************************************
This file is part of the pdi stack.

This is free software. you can redistribute it and/or modify it but without any
warranty.

File            : DeviceIotTable.h
Author          : Suraj I.
created Date    : 1st Jan 2024

Note            : THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
*******************************************************************************/

#ifndef _DEVICEIOTTABLE_H_
#define _DEVICEIOTTABLE_H_

#include <database/core/DatabaseTable.h>

#define DEVICE_IOT_CONFIG_TABLE_ADDRESS 2500

/**
 * @name    DeviceIotTable
 *
 * @purpose DeviceIot table handles iot configs load/store operations
 *
 */
class DeviceIotTable : public DatabaseTable<DEVICE_IOT_CONFIG_TABLE_ADDRESS, device_iot_config_table>
{

  public:
  private:
  protected:
};

extern DeviceIotTable __device_iot_table;

#endif // _DEVICEIOTTABLE_H_
