/*******************************************************************************
This file is part of the pdi stack.

This is free software. you can redistribute it and/or modify it but without any
warranty.

File            : DeviceIotTable.h
Author          : Suraj I.
created Date    : 1st Jan 2024

Note            : THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
*******************************************************************************/

#ifndef _DEVICEIOTTABLE_H_
#define _DEVICEIOTTABLE_H_

#include <database/core/DatabaseTable.h>

/**
 * @name    DeviceIotTable
 *
 * @purpose DeviceIot table handles iot configs load/store operations
 *
 */
class DeviceIotTable : public DatabaseTable<device_iot_config_table>
{

  public:
    /**
     * @purpose Constructor
     */
    DeviceIotTable()
    {
    }

    /**
     * @purpose Destructor
     */
    ~DeviceIotTable()
    {
    }

    /**
     * @purpose register table to database.
     */
    void boot()
    {
        this->register_table(DEVICE_IOT_CONFIG_TABLE_ADDRESS);
    }

    /**
     * @purpose get/fetch table from database.
     */
    bool get(device_iot_config_table *_table)
    {
        return this->get_table(DEVICE_IOT_CONFIG_TABLE_ADDRESS, _table);
    }

    /**
     * @purpose set table from database.
     */
    bool set(device_iot_config_table *_table)
    {
        return this->set_table(DEVICE_IOT_CONFIG_TABLE_ADDRESS, _table);
    }

    /**
     * @purpose clear table in database.
     */
    void clear()
    {
        this->clear_table(DEVICE_IOT_CONFIG_TABLE_ADDRESS);
    }

  private:
  protected:
};

extern DeviceIotTable __device_iot_table;

#endif // _DEVICEIOTTABLE_H_
