/*******************************************************************************
This file is part of the pdi stack.

This is free software. you can redistribute it and/or modify it but without any
warranty.

File            : EmailTable.h
Author          : Suraj I.
created Date    : 1st Jan 2024

Note            : THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
*******************************************************************************/

#ifndef _EMAILTABLE_H_
#define _EMAILTABLE_H_

#include <database/core/DatabaseTable.h>

#define EMAIL_CONFIG_TABLE_ADDRESS 1900

/**
 * @name    EmailTable
 *
 * @purpose Email table handles email service related config load/store operations
 *
 */
class EmailTable : public DatabaseTable<EMAIL_CONFIG_TABLE_ADDRESS, email_config_table>
{

  public:
  private:
  protected:
};

extern EmailTable __email_table;

#endif // _EMAILTABLE_H_
