/*******************************************************************************
This file is part of the Ewings Esp Stack.

This is free software. you can redistribute it and/or modify it but without any
warranty.

File            : EmailTable.h
Author          : Suraj I.
created Date    : 1st Jan 2024

Note            : THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
*******************************************************************************/

#ifndef _EMAILTABLE_H_
#define _EMAILTABLE_H_

#include <database/core/DatabaseTable.h>

/**
 * @name    EmailTable
 *
 * @purpose Email table handles email service related config load/store operations
 *
 */
class EmailTable : public DatabaseTable<email_config_table>
{

  public:
    /**
     * @purpose Constructor
     */
    EmailTable()
    {
    }

    /**
     * @purpose Destructor
     */
    ~EmailTable()
    {
    }

    /**
     * @purpose register table to database.
     */
    void boot()
    {
        this->register_table(EMAIL_CONFIG_TABLE_ADDRESS);
    }

    /**
     * @purpose get/fetch table from database.
     */
    bool get(email_config_table *_table)
    {
        return this->get_table(_table, EMAIL_CONFIG_TABLE_ADDRESS);
    }

    /**
     * @purpose set table from database.
     */
    bool set(email_config_table *_table)
    {
        return this->set_table(_table, EMAIL_CONFIG_TABLE_ADDRESS);
    }

    /**
     * @purpose clear table in database.
     */
    void clear()
    {
        this->clear_table(EMAIL_CONFIG_TABLE_ADDRESS);
    }

  private:
  protected:
};

extern EmailTable __email_table;

#endif // _EMAILTABLE_H_
