/*******************************************************************************
This file is part of the pdi stack.

This is free software. you can redistribute it and/or modify it but without any
warranty.

File            : GlobalTable.h
Author          : Suraj I.
created Date    : 1st Jan 2024

Note            : THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
*******************************************************************************/

#ifndef _GLOBALTABLE_H_
#define _GLOBALTABLE_H_

#include <database/core/DatabaseTable.h>

/**
 * @name    GlobalTable
 *
 * @purpose Global table handles global config load/store operations
 *
 */
class GlobalTable : public DatabaseTable<GLOBAL_CONFIG_TABLE_ADDRESS, global_config_table>
{

  public:
  private:
  protected:
};

extern GlobalTable __global_table;

#endif // _GLOBALTABLE_H_
