/*******************************************************************************
This file is part of the pdi stack.

This is free software. you can redistribute it and/or modify it but without any
warranty.

File            : GpioTable.h
Author          : Suraj I.
created Date    : 1st Jan 2024

Note            : THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
*******************************************************************************/

#ifndef _GPIOTABLE_H_
#define _GPIOTABLE_H_

#include <database/core/DatabaseTable.h>

/**
 * @name    GpioTable
 *
 * @purpose GPIO table handles GPIO configs load/store operations
 *
 */
class GpioTable : public DatabaseTable<gpio_config_table>
{

  public:
    /**
     * @purpose Constructor
     */
    GpioTable()
    {
    }

    /**
     * @purpose Destructor
     */
    ~GpioTable()
    {
    }

    /**
     * @purpose register table to database.
     */
    void boot()
    {
        this->register_table(GPIO_CONFIG_TABLE_ADDRESS);
    }

    /**
     * @purpose get/fetch table from database.
     */
    bool get(gpio_config_table *_table)
    {
        return this->get_table(GPIO_CONFIG_TABLE_ADDRESS, _table);
    }

    /**
     * @purpose set table from database.
     */
    bool set(gpio_config_table *_table)
    {
        return this->set_table(GPIO_CONFIG_TABLE_ADDRESS, _table);
    }

    /**
     * @purpose clear table in database.
     */
    void clear()
    {
        this->clear_table(GPIO_CONFIG_TABLE_ADDRESS);
    }

  private:
  protected:
};

extern GpioTable __gpio_table;

#endif // _GPIOTABLE_H_
