/*******************************************************************************
This file is part of the pdi stack.

This is free software. you can redistribute it and/or modify it but without any
warranty.

File            : GpioTable.h
Author          : Suraj I.
created Date    : 1st Jan 2024

Note            : THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
*******************************************************************************/

#ifndef _GPIOTABLE_H_
#define _GPIOTABLE_H_

#include <database/core/DatabaseTable.h>

/**
 * @name    GpioTable
 *
 * @purpose GPIO table handles GPIO configs load/store operations
 *
 */
class GpioTable : public DatabaseTable<GPIO_CONFIG_TABLE_ADDRESS, gpio_config_table>
{

  public:
  private:
  protected:
};

extern GpioTable __gpio_table;

#endif // _GPIOTABLE_H_
