/*******************************************************************************
This file is part of the Ewings Esp Stack.

This is free software. you can redistribute it and/or modify it but without any
warranty.

File            : LoginTable.h
Author          : Suraj I.
created Date    : 1st Jan 2024

Note            : THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
*******************************************************************************/

#ifndef _LOGINTABLE_H_
#define _LOGINTABLE_H_

#include <database/core/DatabaseTable.h>

/**
 * @name    LoginTable
 *
 * @purpose Login table handles credential configs load/store operations
 *
 */
class LoginTable : public DatabaseTable<login_credential_table>
{

  public:
    /**
     * @purpose Constructor
     */
    LoginTable()
    {
    }

    /**
     * @purpose Destructor
     */
    ~LoginTable()
    {
    }

    /**
     * @purpose register table to database.
     */
    void boot()
    {
        this->register_table(LOGIN_CREDENTIAL_TABLE_ADDRESS);
    }

    /**
     * @purpose get/fetch table from database.
     */
    bool get(login_credential_table *_table)
    {
        return this->get_table(LOGIN_CREDENTIAL_TABLE_ADDRESS, _table);
    }

    /**
     * @purpose set table from database.
     */
    bool set(login_credential_table *_table)
    {
        return this->set_table(LOGIN_CREDENTIAL_TABLE_ADDRESS, _table);
    }

    /**
     * @purpose clear table in database.
     */
    void clear()
    {
        this->clear_table(LOGIN_CREDENTIAL_TABLE_ADDRESS);
    }

  private:
  protected:
};

extern LoginTable __login_table;

#endif // _LOGINTABLE_H_
