/*******************************************************************************
This file is part of the pdi stack.

This is free software. you can redistribute it and/or modify it but without any
warranty.

File            : MqttGeneralTable.h
Author          : Suraj I.
created Date    : 1st Jan 2024

Note            : THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
*******************************************************************************/

#ifndef _MQTTGENERALTABLE_H_
#define _MQTTGENERALTABLE_H_

#include <database/core/DatabaseTable.h>

/**
 * @name    MqttGeneralTable
 *
 * @purpose MqttGeneral table handles general configs load/store operations
 *
 */
class MqttGeneralTable : public DatabaseTable<mqtt_general_config_table>
{

  public:
    /**
     * @purpose Constructor
     */
    MqttGeneralTable()
    {
    }

    /**
     * @purpose Destructor
     */
    ~MqttGeneralTable()
    {
    }

    /**
     * @purpose register table to database.
     */
    void boot()
    {
        this->register_table(MQTT_GENERAL_CONFIG_TABLE_ADDRESS);
    }

    /**
     * @purpose get/fetch table from database.
     */
    bool get(mqtt_general_config_table *_table)
    {
        return this->get_table(MQTT_GENERAL_CONFIG_TABLE_ADDRESS, _table);
    }

    /**
     * @purpose set table from database.
     */
    bool set(mqtt_general_config_table *_table)
    {
        return this->set_table(MQTT_GENERAL_CONFIG_TABLE_ADDRESS, _table);
    }

    /**
     * @purpose clear table in database.
     */
    void clear()
    {
        this->clear_table(MQTT_GENERAL_CONFIG_TABLE_ADDRESS);
    }

  private:
  protected:
};

extern MqttGeneralTable __mqtt_general_table;

#endif // _MQTTGENERALTABLE_H_
