/*******************************************************************************
This file is part of the Ewings Esp Stack.

This is free software. you can redistribute it and/or modify it but without any
warranty.

File            : OtaTable.h
Author          : Suraj I.
created Date    : 1st Jan 2024

Note            : THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
*******************************************************************************/

#ifndef _OTATABLE_H_
#define _OTATABLE_H_

#include <database/core/DatabaseTable.h>

/**
 * @name    OtaTable
 *
 * @purpose OTA table handles ota server configs load/store operations
 *
 */
class OtaTable : public DatabaseTable<ota_config_table>
{

  public:
    /**
     * @purpose Constructor
     */
    OtaTable()
    {
    }

    /**
     * @purpose Destructor
     */
    ~OtaTable()
    {
    }

    /**
     * @purpose register table to database.
     */
    void boot()
    {
        this->register_table(OTA_CONFIG_TABLE_ADDRESS);
    }

    /**
     * @purpose get/fetch table from database.
     */
    bool get(ota_config_table *_table)
    {
        return this->get_table(OTA_CONFIG_TABLE_ADDRESS, _table);
    }

    /**
     * @purpose set table from database.
     */
    bool set(ota_config_table *_table)
    {
        return this->set_table(OTA_CONFIG_TABLE_ADDRESS, _table);
    }

    /**
     * @purpose clear table in database.
     */
    void clear()
    {
        this->clear_table(OTA_CONFIG_TABLE_ADDRESS);
    }

  private:
  protected:
};

extern OtaTable __ota_table;

#endif // _OTATABLE_H_
