/*******************************************************************************
This file is part of the pdi stack.

This is free software. you can redistribute it and/or modify it but without any
warranty.

File            : WiFiTable.h
Author          : Suraj I.
created Date    : 1st Jan 2024

Note            : THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
*******************************************************************************/

#ifndef _WIFITABLE_H_
#define _WIFITABLE_H_

#include <database/core/DatabaseTable.h>

#define WIFI_CONFIG_TABLE_ADDRESS 150

/**
 * @name    WiFiTable
 *
 * @purpose Wifi table handles wifi configs load/store operations
 *
 */
class WiFiTable : public DatabaseTable<WIFI_CONFIG_TABLE_ADDRESS, wifi_config_table>
{

  public:
  private:
  protected:
};

extern WiFiTable __wifi_table;

#endif // _WIFITABLE_H_
